/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Ore.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_OreBase : public EntityCall
{
public:

	EntityBaseEntityCall_OreBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_OreBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_OreBase : public EntityCall
{
public:

	EntityCellEntityCall_OreBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_OreBase();
};

}