/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/World.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_WorldBase : public EntityCall
{
public:

	EntityBaseEntityCall_WorldBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_WorldBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_WorldBase : public EntityCall
{
public:

	EntityCellEntityCall_WorldBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_WorldBase();
};

}