/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/ItemDropPackage.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_ItemDropPackageBase : public EntityCall
{
public:

	EntityBaseEntityCall_ItemDropPackageBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_ItemDropPackageBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_ItemDropPackageBase : public EntityCall
{
public:

	EntityCellEntityCall_ItemDropPackageBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_ItemDropPackageBase();
};

}