/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/SceneMgr.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_SceneMgrBase : public EntityCall
{
public:

	EntityBaseEntityCall_SceneMgrBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_SceneMgrBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_SceneMgrBase : public EntityCall
{
public:

	EntityCellEntityCall_SceneMgrBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_SceneMgrBase();
};

}