/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Avatar.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_AvatarBase : public EntityCall
{
public:

	EntityBaseEntityCall_AvatarBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_AvatarBase();
	void reqSwitchAvatar();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_AvatarBase : public EntityCall
{
public:

	EntityCellEntityCall_AvatarBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_AvatarBase();
	void AnimUpdate(const ANIM_INFO& arg1);
	void Attack(const SKILL_INFO& arg1);
	void Relive();
	void ReqChangeEnage(int32 arg1);
	void ReqStartDamage(const SKILL_INFO& arg1, const ENTITY_LIST& arg2);
	void reqChangeJump(int8 arg1);
	void reqChangeMoveH(int8 arg1);
	void reqChangeMoveLevel(int8 arg1);
	void reqChangeMoveV(int8 arg1);
	void reqChangeName(const FString& arg1);
	void reqDigOre(int32 arg1);
	void reqExecInnerFunc(const FString& arg1, const FString& arg2);
	void reqMoveItem(uint16 arg1, uint16 arg2);
	void reqPickupItem(int32 arg1, const UINT64_LIST& arg2);
	void reqSendChatMessage(uint64 arg1, uint8 arg2, const FString& arg3);
	void reqSetupInnerProp(const FString& arg1, const FString& arg2);
	void reqSplitItemNum(uint16 arg1, uint32 arg2, uint16 arg3);
	void reqStopDigOre();
};

}