/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Monster.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_MonsterBase : public EntityCall
{
public:

	EntityBaseEntityCall_MonsterBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_MonsterBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_MonsterBase : public EntityCall
{
public:

	EntityCellEntityCall_MonsterBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_MonsterBase();
	void AnimUpdate(const ANIM_INFO& arg1);
	void Attack(const SKILL_INFO& arg1);
	void Relive();
	void ReqChangeEnage(int32 arg1);
	void ReqStartDamage(const SKILL_INFO& arg1, const ENTITY_LIST& arg2);
};

}