/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Scene.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_SceneBase : public EntityCall
{
public:

	EntityBaseEntityCall_SceneBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_SceneBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_SceneBase : public EntityCall
{
public:

	EntityCellEntityCall_SceneBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_SceneBase();
};

}