/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class ItemDropPackage : public ItemDropPackageBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallItemDropPackageBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/ItemDropPackage.def
	// Please inherit and implement "class ItemDropPackage : public ItemDropPackageBase"
class KBENGINEPLUGINS_API ItemDropPackageBase : public Entity
{
public:
	EntityBaseEntityCall_ItemDropPackageBase* pBaseEntityCall;
	EntityCellEntityCall_ItemDropPackageBase* pCellEntityCall;

	ITEM_LIST dropItems;
	virtual void onDropItemsChanged(const ITEM_LIST& oldValue) {}
	uint64 ownerDBID;
	virtual void onOwnerDBIDChanged(uint64 oldValue) {}


	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	ItemDropPackageBase();
	virtual ~ItemDropPackageBase();

	void attachComponents() override;
	void detachComponents() override;

};

}