/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Scene : public SceneBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallSceneBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/Scene.def
	// Please inherit and implement "class Scene : public SceneBase"
class KBENGINEPLUGINS_API SceneBase : public Entity
{
public:
	EntityBaseEntityCall_SceneBase* pBaseEntityCall;
	EntityCellEntityCall_SceneBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	SceneBase();
	virtual ~SceneBase();

	void attachComponents() override;
	void detachComponents() override;

};

}