/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class World : public WorldBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallWorldBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/World.def
	// Please inherit and implement "class World : public WorldBase"
class KBENGINEPLUGINS_API WorldBase : public Entity
{
public:
	EntityBaseEntityCall_WorldBase* pBaseEntityCall;
	EntityCellEntityCall_WorldBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	WorldBase();
	virtual ~WorldBase();

	void attachComponents() override;
	void detachComponents() override;

};

}